import React, { useState } from 'react';
import { BugTicket, AnalysisResult } from './types';
import { analyzeBugWithGemini } from './geminiService';
import { AlertCircle, Clock, Cpu, ExternalLink, FileText, Copy, Check, Github, CheckCircle2 } from 'lucide-react';

interface BugDetailProps {
  bug: BugTicket;
  onBack: () => void;
  onAddActivity: (action: string, details: string, type: 'commit' | 'analysis' | 'comment' | 'pr' | 'system') => void;
  onResolve: (id: string) => void;
}

const BugDetail: React.FC<BugDetailProps> = ({ bug, onBack, onAddActivity, onResolve }) => {
  const [analyzing, setAnalyzing] = useState(false);
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const handleAnalyze = async () => {
    setAnalyzing(true);
    setErrorMessage(null);
    onAddActivity("Started Analysis", `Analyzing bug #${bug.id} using Gemini 2.5 Flash`, 'analysis');
    try {
      const result = await analyzeBugWithGemini(bug.title, bug.description, bug.repository);
      setAnalysis(result);
      onAddActivity("Analysis Complete", "Root cause identified and solution proposed.", 'analysis');
    } catch (error) {
      console.error(error);
      setErrorMessage("Analysis failed. Please try again.");
      onAddActivity("Analysis Failed", "Could not complete AI analysis.", 'system');
    } finally {
      setAnalyzing(false);
    }
  };

  const handleCopy = () => {
    if (!analysis) return;

    // Copy the suggested GitHub comment if available, otherwise fallback to the structured report
    const contentToCopy = analysis.suggestedGitComment || `## AI Analysis Report for #${bug.id}

### Root Cause
${analysis.rootCause}

### Proposed Solution
${analysis.proposedSolution}

### Files to Modify
${analysis.filesToModify.map(f => `- ${f}`).join('\n')}

---
*Generated by Junior Bug-Fixing Agent*`;

    navigator.clipboard.writeText(contentToCopy);
    setCopied(true);
    onAddActivity("Report Copied", "User copied analysis report to clipboard", 'system');
    
    // Mark as resolved in the system
    onResolve(bug.id);

    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-col h-full bg-github-bg text-github-text animate-fade-in">
      {/* Header */}
      <div className="mb-6 pb-4 border-b border-github-border">
        <button 
          onClick={onBack}
          className="text-sm text-blue-400 hover:underline mb-2 flex items-center gap-1"
        >
          ← Back to Dashboard
        </button>
        <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl font-semibold text-white flex items-center gap-2">
              {bug.title} <span className="text-github-muted font-normal">#{bug.id}</span>
            </h1>
            <div className="flex flex-wrap items-center gap-2 mt-2">
              <span className={`px-2 py-0.5 rounded-full text-xs font-medium border flex items-center gap-1 ${
                bug.status === 'open' 
                  ? 'bg-green-900/40 text-green-400 border-green-900' 
                  : bug.status === 'resolved'
                    ? 'bg-blue-900/40 text-blue-400 border-blue-900'
                    : 'bg-purple-900/40 text-purple-400 border-purple-900'
              }`}>
                {bug.status === 'resolved' ? <CheckCircle2 className="w-3 h-3" /> : <AlertCircle className="w-3 h-3" />} 
                {bug.status.toUpperCase()}
              </span>
              <span className="text-github-muted text-sm flex items-center gap-1">
                <Clock className="w-3 h-3" /> {bug.assignedAt ? `Opened ${new Date(bug.assignedAt).toLocaleDateString()}` : 'Date unknown'} by {bug.author}
              </span>
               {bug.url && (
                <a href={bug.url} target="_blank" rel="noreferrer" className="text-github-muted text-sm hover:text-blue-400 flex items-center gap-1 ml-2">
                   <ExternalLink className="w-3 h-3" /> View on GitHub
                </a>
              )}
            </div>
          </div>
          <div className="flex gap-2">
            {!analysis && (
              <button 
                onClick={handleAnalyze}
                disabled={analyzing}
                className="flex items-center gap-2 px-4 py-2 bg-github-accent text-white rounded-md text-sm font-medium hover:bg-blue-600 transition-colors disabled:opacity-50"
              >
                {analyzing ? (
                  <><Cpu className="w-4 h-4 animate-spin" /> Analyzing...</>
                ) : (
                  <><Cpu className="w-4 h-4" /> AI Analyzer</>
                )}
              </button>
            )}
            {analysis && (
              <button 
                onClick={handleCopy}
                className="flex items-center gap-2 px-4 py-2 bg-github-btn border border-github-border text-white rounded-md text-sm font-medium hover:bg-github-btnHover transition-colors"
              >
                 {copied ? (
                  <><Check className="w-4 h-4 text-green-400" /> Copied!</>
                ) : (
                  <><Copy className="w-4 h-4" /> Copy Report to Clipboard</>
                )}
              </button>
            )}
          </div>
        </div>
        {errorMessage && (
            <div className="mt-4 p-3 bg-red-900/20 border border-red-900/50 rounded-md flex items-center gap-2 text-red-200 text-sm">
                <AlertCircle className="w-4 h-4 text-red-400" />
                {errorMessage}
            </div>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Column */}
        <div className="lg:col-span-2 space-y-6">
          
          {/* Description */}
          <div className="bg-github-card border border-github-border rounded-md">
            <div className="bg-github-btn/50 px-4 py-2 border-b border-github-border flex justify-between items-center">
              <span className="font-semibold text-sm">Description</span>
            </div>
            <div className="p-4 text-sm leading-relaxed whitespace-pre-wrap font-sans text-gray-300">
              {bug.description}
            </div>
          </div>

          {/* AI Analysis Result */}
          {analysis && (
            <div className="space-y-6 animate-slide-up">
              {/* Internal Analysis */}
              <div className="bg-github-card border border-github-border rounded-md overflow-hidden">
                <div className="bg-gradient-to-r from-blue-900/20 to-purple-900/20 px-4 py-2 border-b border-github-border flex justify-between items-center">
                  <span className="font-semibold text-sm flex items-center gap-2 text-blue-300">
                    <Cpu className="w-4 h-4" /> AI Analysis Report
                  </span>
                  <div className="flex items-center gap-2">
                     <span className="text-xs bg-blue-900/50 text-blue-200 px-2 py-0.5 rounded border border-blue-800">
                      Confidence: {analysis.confidence}%
                    </span>
                  </div>
                </div>
                <div className="p-4 space-y-4">
                  <div>
                    <h4 className="text-sm font-medium text-white mb-1">Root Cause</h4>
                    <p className="text-sm text-github-muted">{analysis.rootCause}</p>
                  </div>
                  <div>
                    <h4 className="text-sm font-medium text-white mb-1">Proposed Solution</h4>
                    <p className="text-sm text-github-muted">{analysis.proposedSolution}</p>
                  </div>
                  <div>
                    <h4 className="text-sm font-medium text-white mb-2">Affected Files</h4>
                    <div className="flex flex-wrap gap-2">
                      {analysis.filesToModify.map(file => (
                        <span key={file} className="flex items-center gap-1 text-xs bg-github-btn border border-github-border px-2 py-1 rounded text-github-text">
                          <FileText className="w-3 h-3" /> {file}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              {/* Generated GitHub Content */}
              <div className="bg-github-card border border-github-border rounded-md overflow-hidden">
                <div className="bg-github-btn/50 px-4 py-2 border-b border-github-border flex justify-between items-center">
                  <span className="font-semibold text-sm flex items-center gap-2">
                    <Github className="w-4 h-4" /> Suggested GitHub Update
                  </span>
                  <span className="text-xs text-github-muted">Ready to paste</span>
                </div>
                <div className="p-4 bg-[#0d1117]">
                  <pre className="text-sm text-gray-300 font-mono whitespace-pre-wrap overflow-x-auto">
                    {analysis.suggestedGitComment}
                  </pre>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Sidebar */}
        <div className="space-y-6">
          <div className="bg-github-card border border-github-border rounded-md p-4">
            <h3 className="text-sm font-bold text-github-muted uppercase mb-3">Labels</h3>
            <div className="flex flex-wrap gap-2">
              {bug.labels.map(label => (
                <span key={label} className="px-2 py-1 rounded-full text-xs font-medium bg-blue-900/30 text-blue-300 border border-blue-900/50">
                  {label}
                </span>
              ))}
            </div>
          </div>

          <div className="bg-github-card border border-github-border rounded-md p-4">
            <h3 className="text-sm font-bold text-github-muted uppercase mb-3">Details</h3>
            <div className="space-y-3 text-sm">
              <div className="flex justify-between">
                <span className="text-github-muted">Repository</span>
                <span className="font-medium text-white">{bug.repository}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-github-muted">Severity</span>
                <span className={`font-medium ${
                  bug.severity === 'critical' ? 'text-red-400' : 
                  bug.severity === 'high' ? 'text-orange-400' : 'text-yellow-400'
                }`}>
                  {bug.severity.charAt(0).toUpperCase() + bug.severity.slice(1)}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-github-muted">Est. Effort</span>
                <span className="font-medium text-white">{bug.estimatedCompletion} mins</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BugDetail;